
hotkey.qwerty_hotkey = "ctrl-cmd-space"

find_apps = true
find_executables = true

dirs = ["/System/Applications/", "/Applications/", "/System/Applications/Utilities/", "/System/Library/CoreServices/", "~/.unmenu-bin"]

ignore_names = [
        "unmenu.app", # we don't want to launch ourselves, right?

        ".Karabiner-VirtualHIDDevice-Manager.app",

        # Mostly not very useful things from /System/Library/CoreServices
        "Install Command Line Developer Tools.app",
        "Install in Progress.app",
        "Migration Assistant.app",
        "TextInputMenuAgent.app",
        "TextInputSwitcher.app",
        "AOSUIPrefPaneLauncher.app",
        "Automator Application Stub.app",
        "NetAuthAgent.app",
        "Captive Network Assistant.app",
        "screencaptureui.app",
        "ScreenSaverEngine.app",
        "SystemUIServer.app",
        "UIKitSystem.app",
        "NowPlayingTouchUI.app",
        "WindowManager.app",
        "APFSUserAgent",
        "AVB Audio Configuration.app",
        "AddPrinter.app",
        "AddressBookUrlForwarder.app",
        "AirPlayUIAgent.app",
        "AirPort Base Station Agent.app",
        "AppleScript Utility.app",
        "Automator Application Stub.app",
        "Automator Installer.app",
        "BluetoothSetupAssistant.app",
        "BluetoothUIServer.app",
        "BluetoothUIService.app",
        "CSUserAgent",
        "CalendarFileHandler.app",
        "Captive Network Assistant.app",
        "Certificate Assistant.app",
        "CloudSettingsSyncAgent",
        "ControlCenter.app",
        "ControlStrip.app",
        "CoreLocationAgent.app",
        "CoreServicesUIAgent.app",
        "Coverage Details.app",
        "CrashReporterSupportHelper",
        "DMProxy",
        "Database Events.app",
        "DefaultBackground.jpg",
        "DefaultDesktop.heic",
        "Diagnostics Reporter.app",
        "DiscHelper.app",
        "DiskImageMounter.app",
        "Dock.app",
        "Dwell Control.app",
        "Erase Assistant.app",
        "EscrowSecurityAlert.app",
        "ExpansionSlotNotification",
        "FolderActionsDispatcher.app",
        "HelpViewer.app",
        "IOUIAgent.app",
        "Image Events.app",
        "Install Command Line Developer Tools.app",
        "Install in Progress.app",
        "Installer Progress.app",
        "Installer.app",
        "JavaLauncher.app",
        "KeyboardAccessAgent.app",
        "KeyboardSetupAssistant.app",
        "Keychain Circle Notification.app",
        "Language Chooser.app",
        "MTLReplayer.app",
        "ManagedClient.app",
        "MapsSuggestionsTransportModePrediction.mlmodelc",
        "MemorySlotNotification",
        "Menu Extras",
        "NetAuthAgent.app",
        "NowPlayingTouchUI.app",
        "OBEXAgent.app",
        "ODSAgent.app",
        "OSDUIHelper.app",
        "PIPAgent.app",
        "PodcastsAuthAgent.app",
        "PowerChime.app",
        "Pro Display Calibrator.app",
        "Problem Reporter.app",
        "ProfileHelper.app",
        "RapportUIAgent.app",
        "RegisterPluginIMApp.app",
        "RemoteManagement",
        "RemotePairTool",
        "ReportCrash",
        "Resources",
        "RestoreVersion.plist",
        "Rosetta 2 Updater.app",
        "ScopedBookmarkAgent",
        "ScreenSaverEngine.app",
        "Script Menu.app",
        "ScriptMonitor.app",
        "SecurityAgentPlugins",
        "ServicesUIAgent",
        "Setup Assistant.app",
        "SetupAssistantPlugins",
        "ShortcutDroplet.app",
        "Shortcuts Events.app",
        "SpacesTouchBarAgent.app",
        "StageManagerEducation.app",
        "SubmitDiagInfo",
        "SystemFolderLocalizations",
        "SystemUIServer.app",
        "SystemVersion.plist",
        "SystemVersionCompat.plist",
        "TextInputMenuAgent.app",
        "TextInputSwitcher.app",
        "ThermalTrap.app",
        "Tips.app",
        "UAUPlugins",
        "UIKitSystem.app",
        "UniversalAccessControl.app",
        "UniversalControl.app",
        "UnmountAssistantAgent.app",
        "UserAccountUpdater",
        "UserNotificationCenter.app",
        "UserPictureSyncAgent",
        "VoiceOver.app",
        "WatchFaceAlert.app",
        "WiFiAgent.app",
        "WidgetKit Simulator.app",
        "WindowManager.app",
        "Xcode Previews.app",
        "appleeventsd",
        "boot.efi",
        "cacheTimeZones",
        "cloudpaird",
        "com.apple.NSServicesRestrictions.plist",
        "coreservicesd",
        "destinationd",
        "diagnostics_agent",
        "iCloud+.app",
        "iCloud.app",
        "iOSSystemVersion.plist",
        "iTunesStoreURLPatterns.plist",
        "iconservicesagent",
        "iconservicesd",
        "ionodecache",
        "launchservicesd",
        "lockoutagent",
        "logind",
        "loginwindow.app",
        "mapspushd",
        "navd",
        "osanalyticshelper",
        "pbs",
        "rc.trampoline",
        "rcd.app",
        "screencaptureui.app",
        "sessionlogoutd",
        "sharedfilelistd",
        "talagent",
        "uncd",

        "NotificationCenter.app",
        ]
ignore_patterns = [
        "^Install.*",
        ".*Installer\\.app$",
        "\\.bundle$"
        ]

